# Test your FastAPI endpoints

###
POST http://127.0.0.1:8000/registration
Accept: application/json
Content-Type: application/json

{
  "username": "string1",
  "email": "string1",
  "full_name": "string",
  "disabled": false,
  "password": "string"
}
###
POST http://127.0.0.1:8000/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=&username=johndoe&password=secret&scope=&client_id=&client_secret=
###
GET http://127.0.0.1:8000/users/me
Accept: application/json
Authorization: Bearer {{token}}
###
GET http://127.0.0.1:8000/users/me/notes
Accept: application/json
Authorization: Bearer {{token}}
###
GET http://127.0.0.1:8000/notes
Accept: application/json
###
GET http://127.0.0.1:8000/notes/1
Accept: application/json
###
PUT http://127.0.0.1:8000/notes/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "string1",
  "content": "string1",
  "tags": [
    {"tag_name": "Foo"},
    {"tag_name": "Bar"}
  ]
}
###
POST http://127.0.0.1:8000/notes/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "string",
  "content": "string",
  "tags": []
}
###
POST http://127.0.0.1:8000/tags/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "tag_name": "string"
  }
]